### PR TITLE
Removed destructuring

### PR DESCRIPTION
**Pull request by t-sauer**
For Node 4 compatibility.  
Tests are passing for me so maybe Node 4 can be added for Travis again?

### CODE REVIEW

**Comment by rwjblue** [comment]
Yes, please update .travis.yml if you don't mind?

**Comment by t-sauer** [comment]
I have no idea why this is failing on travis now.

**Comment by t-sauer** [comment]
@rwjblue Seems to be working now.

**Comment by dgeb** [comment]
Thanks @t-sauer! I've been meaning to come back and fix up support for node 4.

**Pull request merged**
